### ISSUE TITLE
Changing configuration (e.g. frequent_scan_interval) doesn't work

### ISSUE THREAD

**Issue by olli-dot-dev** [weltenwort/home-assistant-rct-power-integration#483]
## Version of the custom_component

0.14.1

## Configuration

Not relevant 

## Describe the bug

Changing the configuration later does not work because the entries are not saved. For example changing the value of frequent_scan_interval is not possible.

I navigate to Integrations and select RCT Power within. In the section "Integrationseinträge" I click on "KONFIGURIEREN" and then enter "50" as value for frequent_scan_interval. I hit OK and the dialogue closes telling "Erfolg Optionen wurden erfolgreich gespeichert." but no changes are being saved.

## Debug log

```
No logging given by the integration regarding the problem.

```

**Comment by phinotv** [comment]
Logger: homeassistant.helpers.frame
Quelle: helpers/frame.py:335
Erstmals aufgetreten: 18:07:57 (1 Vorkommnis)
Zuletzt protokolliert: 18:07:57
Detected that custom integration 'rct_power' sets option flow config_entry explicitly, which is deprecated at custom_components/rct_power/config_flow.py, line 69: self.config_entry = config_entry. This will stop working in Home Assistant 2025.12, please create a bug report at https://github.com/weltenwort/home-assistant-rct-power-integration/issues
---------
Logger: homeassistant.config_entries
Quelle: config_entries.py:749
Erstmals aufgetreten: 13:58:47 (1 Vorkommnis)
Zuletzt protokolliert: 13:58:47
Error setting up entry RCT Power Inverter at 192.168.123.70:8899 for rct_power

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/rct_power/__init__.py", line 125, in async_setup_entry
    hass.config_entries.async_forward_entry_setup(entry, platform),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?

**These errors since 17.06.25** No logging for Data
